resolver: lts-15.14

ghc-options: {"$locals": -fwrite-ide-info -fmax-relevant-binds=0}

packages:
  - aura/
  - aur/
  - aursec/

extra-deps:
  - aeson-1.5.0.0  # Pinned to avoid `these` dependency.
  - language-bash-0.9.2
  - rio-0.1.16.0   # Can be removed once this version is in the LTS.
