#! /bin/sh


sxhkd &
xss-lock -- /home/suren/.config/i3/scripts/lock.sh &
telegram-desktop &
/home/suren/.config/polybar/spotify/launchlistener.sh &
~/.config/polybar/launch.sh &


bspc monitor HDMI1 -d I II III IV V VI 
bspc monitor DP1 -d VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle      true
bspc config mark-ovredir-focused false

bspc rule -a TelegramDesktop desktop='^9'
bspc rule -a Spotify desktop='^10'

# rules for floating apps
bspc rule -a Pavucontrol state=floating
bspc rule -a htop state=floating
bspc rule -a nethogs state=floating
bspc rule -a Maltego state=floating
bspc rule -a burp-StartBurp state=floating
bspc rule -a Transmission-gtk state=floating


